# Generated by Django 2.1.15 on 2021-04-13 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.Recipe'),
            preserve_default=False,
        ),
    ]
